.PHONY: clean All

All:
	@echo "----------Building project:[ capstone - Debug ]----------"
	@cd "capstone" && "$(MAKE)" -f  "capstone.mk"
clean:
	@echo "----------Cleaning project:[ capstone - Debug ]----------"
	@cd "capstone" && "$(MAKE)" -f  "capstone.mk" clean
