.PHONY: clean All

All:
	@echo "----------Building project:[ weather_map - Debug ]----------"
	@cd "weather_map" && "$(MAKE)" -f  "weather_map.mk"
clean:
	@echo "----------Cleaning project:[ weather_map - Debug ]----------"
	@cd "weather_map" && "$(MAKE)" -f  "weather_map.mk" clean
